[package]
name = "pmix-sys"
version = "0.1.0"
edition = "2021"
links = "pmix"
build = "build.rs"
authors = ["Ryan D. Friese <ryan.friese@pnnl.gov>"]
description = "Low-level FFI bindings to PMIx, developed for use by the Lamellar runtime."
readme = "README.md"
repository = "https://github.com/pnnl/lamellar"
homepage = "https://github.com/pnnl/lamellar"
license-file = "LICENSE"
keywords = ["hpc", "pmi", "process-management"]
categories = ["external-ffi-bindings", "network-programming"]


[features]
vendored = ["openpmix-src", "vendored-hwloc", "vendored-libevent"]
vendored-hwloc = ["hwlocality-sys/hwloc-latest", "hwlocality-sys/vendored", "openpmix-src/vendored-hwloc"]
vendored-libevent = ["libevent-sys/bundled", "libevent-sys/openssl_bundled", "openpmix-src/vendored-libevent"]

[dependencies]
hwlocality-sys = { version = "0.7.1", optional = true }
libevent-sys = { version = "0.4.0", features = [
    "threading",
], optional = true }

[build-dependencies]
openpmix-src = { version = "0.1.0", optional = true }
bindgen = "0.72.1"
