#!/bin/bash
# Auto-generated by build.rs - DO NOT EDIT
# Source this file before running lamellar applications
# Usage: source lamellar_env.sh

export LD_LIBRARY_PATH=/people/shah229/Projects/lamellar/agent-skills/target/debug/build/lamellar-ucx-sys-d01b253dae1ff761/out/lib:/people/shah229/Projects/lamellar/agent-skills/target/debug/build/pmix-sys-aa17783f94163b73/out/lib:$LD_LIBRARY_PATH
