[package]
name = "pmi"
version = "0.1.0"
edition = "2021"
links = "pminative"
authors = ["Ryan D. Friese <ryan.friese@pnnl.gov>"]
description = "A unified interface over PMI1, PMI2, and PMIx process management, developed for use by the Lamellar runtime."
readme = "README.md"
repository = "https://github.com/pnnl/lamellar"
homepage = "https://github.com/pnnl/lamellar"
license-file = "LICENSE"
keywords = ["hpc", "pmi", "process-management"]
categories = ["external-ffi-bindings", "network-programming"]

[dependencies]
pmi-sys = { version = "0.1.0", optional = true }
pmi2-sys = { version = "0.1.0", optional = true }
pmix-sys = { version = "0.1.0", optional = true }
libc = "0.2"

[features]
with-pmi1 = ["pmi-sys"]
with-pmi2 = ["pmi2-sys"]
with-pmix = ["pmix-sys"]
vendored = ["pmi-sys?/vendored", "pmi2-sys?/vendored", "pmix-sys?/openpmix-src", "pmix-sys?/vendored-libevent"]
with-pmi1-vendored = ["with-pmi1", "vendored"]
with-pmi2-vendored = ["with-pmi2", "vendored"]
with-pmix-vendored = ["with-pmix", "vendored"]
