[package]
name = "prrte-sys"
version = "0.1.0"
edition = "2021"
links = "prrte"
build = "build.rs"
authors = ["Ryan D. Friese <ryan.friese@pnnl.gov>"]
description = "Low-level FFI bindings to PRRTE, developed for use by the Lamellar runtime."
readme = "README.md"
repository = "https://github.com/pnnl/lamellar"
homepage = "https://github.com/pnnl/lamellar"
license-file = "LICENSE"
keywords = ["hpc", "pmi", "process-management"]
categories = ["external-ffi-bindings", "network-programming"]

[features]
vendored = [
    "prrte-src",
    "vendored-libevent",
    "vendored-hwloc",
    "vendored-pmix",
] # Ideally we wouldn't always need the vendored version of the dependencies
# but currently hwloc-sys does not expose a way to get the path to a system-installed hwloc
vendored-libevent = ["libevent-sys/bundled", "libevent-sys/openssl_bundled", "pmix-sys/vendored-libevent"]
vendored-hwloc = ["hwlocality-sys/hwloc-latest", "hwlocality-sys/vendored", "pmix-sys/vendored-hwloc"]
vendored-pmix = ["pmix-sys/openpmix-src"]
vendored-prrte = [
    "prrte-src",
    "vendored-libevent",
    "hwlocality-sys",
    "pmix-sys",
]

[dependencies]
pmix-sys = { version = "0.1.0", optional = true }
libevent-sys = { version = "0.4.0", features = ["threading"], optional = true }
hwlocality-sys = { version = "0.7.1", optional = true }

[build-dependencies]
prrte-src = { version = "0.1.0", optional = true }
bindgen = "0.72.1"
