[package]
name = "prrte-src"
version = "0.1.0-rc.1"
edition = "2024"
authors = ["Ryan D. Friese <ryan.friese@pnnl.gov>"]
description = "Vendored build of PRRTE, developed for use by the Lamellar runtime."
readme = "README.md"
repository = "https://github.com/pnnl/lamellar"
homepage = "https://github.com/pnnl/lamellar"
license-file = "LICENSE"
keywords = ["hpc", "pmi", "process-management"]
categories = ["external-ffi-bindings", "network-programming"]

[dependencies]
autotools = "0.2.7"