/*
 * This file is autogenerated by autogen.pl. Do not edit this file by hand.
 */
#ifndef PMIX_FRAMEWORKS_H
#define PMIX_FRAMEWORKS_H

#include "src/mca/base/pmix_mca_base_framework.h"

extern pmix_mca_base_framework_t pmix_bfrops_base_framework;
extern pmix_mca_base_framework_t pmix_gds_base_framework;
extern pmix_mca_base_framework_t pmix_pcompress_base_framework;
extern pmix_mca_base_framework_t pmix_pdl_base_framework;
extern pmix_mca_base_framework_t pmix_pif_base_framework;
extern pmix_mca_base_framework_t pmix_pinstalldirs_base_framework;
extern pmix_mca_base_framework_t pmix_plog_base_framework;
extern pmix_mca_base_framework_t pmix_pmdl_base_framework;
extern pmix_mca_base_framework_t pmix_pnet_base_framework;
extern pmix_mca_base_framework_t pmix_preg_base_framework;
extern pmix_mca_base_framework_t pmix_psec_base_framework;
extern pmix_mca_base_framework_t pmix_psensor_base_framework;
extern pmix_mca_base_framework_t pmix_psquash_base_framework;
extern pmix_mca_base_framework_t pmix_pstat_base_framework;
extern pmix_mca_base_framework_t pmix_ptl_base_framework;


PMIX_EXPORT extern pmix_mca_base_framework_t *pmix_frameworks[];

PMIX_EXPORT extern char *pmix_framework_names[];

#endif /* PMIX_FRAMEWORKS_H */

