/*
 * This file is autogenerated by construct_event_strings.py.
 * Do not edit this file by hand.
 */

#include "src/include/pmix_config.h"
#include "src/include/pmix_globals.h"
#include "include/pmix_common.h"

#ifndef PMIX_EVENT_STRINGS_H
#define PMIX_EVENT_STRINGS_H

BEGIN_C_DECLS

PMIX_EXPORT extern const pmix_event_string_t pmix_event_strings[163];

#define PMIX_EVENT_INDEX_BOUNDARY 162

END_C_DECLS

#endif

