/*
 * This file is autogenerated by construct_event_strings.py.
 * Do not edit this file by hand.
 */

#include "src/include/pmix_event_strings.h"

const pmix_event_string_t pmix_event_strings[] = {
    {.index = 0, .name = "PMIX_SUCCESS", .code = 0},

    {.index = 1, .name = "PMIX_ERROR", .code = -1},

    {.index = 2, .name = "PMIX_ERR_PROC_RESTART", .code = -4},

    {.index = 3, .name = "PMIX_ERR_PROC_CHECKPOINT", .code = -5},

    {.index = 4, .name = "PMIX_ERR_PROC_MIGRATE", .code = -6},

    {.index = 5, .name = "PMIX_ERR_EXISTS", .code = -11},

    {.index = 6, .name = "PMIX_ERR_INVALID_CRED", .code = -12},

    {.index = 7, .name = "PMIX_ERR_WOULD_BLOCK", .code = -15},

    {.index = 8, .name = "PMIX_ERR_UNKNOWN_DATA_TYPE", .code = -16},

    {.index = 9, .name = "PMIX_ERR_TYPE_MISMATCH", .code = -18},

    {.index = 10, .name = "PMIX_ERR_UNPACK_INADEQUATE_SPACE", .code = -19},

    {.index = 11, .name = "PMIX_ERR_UNPACK_FAILURE", .code = -20},

    {.index = 12, .name = "PMIX_ERR_PACK_FAILURE", .code = -21},

    {.index = 13, .name = "PMIX_ERR_NO_PERMISSIONS", .code = -23},

    {.index = 14, .name = "PMIX_ERR_TIMEOUT", .code = -24},

    {.index = 15, .name = "PMIX_ERR_UNREACH", .code = -25},

    {.index = 16, .name = "PMIX_ERR_BAD_PARAM", .code = -27},

    {.index = 17, .name = "PMIX_ERR_RESOURCE_BUSY", .code = -28},

    {.index = 18, .name = "PMIX_ERR_OUT_OF_RESOURCE", .code = -29},

    {.index = 19, .name = "PMIX_ERR_INIT", .code = -31},

    {.index = 20, .name = "PMIX_ERR_NOMEM", .code = -32},

    {.index = 21, .name = "PMIX_ERR_NOT_FOUND", .code = -46},

    {.index = 22, .name = "PMIX_ERR_NOT_SUPPORTED", .code = -47},

    {.index = 23, .name = "PMIX_ERR_PARAM_VALUE_NOT_SUPPORTED", .code = -59},

    {.index = 24, .name = "PMIX_ERR_COMM_FAILURE", .code = -49},

    {.index = 25, .name = "PMIX_ERR_UNPACK_READ_PAST_END_OF_BUFFER", .code = -50},

    {.index = 26, .name = "PMIX_ERR_CONFLICTING_CLEANUP_DIRECTIVES", .code = -51},

    {.index = 27, .name = "PMIX_ERR_PARTIAL_SUCCESS", .code = -52},

    {.index = 28, .name = "PMIX_ERR_DUPLICATE_KEY", .code = -53},

    {.index = 29, .name = "PMIX_ERR_EMPTY", .code = -60},

    {.index = 30, .name = "PMIX_ERR_LOST_CONNECTION", .code = -61},

    {.index = 31, .name = "PMIX_ERR_EXISTS_OUTSIDE_SCOPE", .code = -62},

    {.index = 32, .name = "PMIX_PROCESS_SET_DEFINE", .code = -55},

    {.index = 33, .name = "PMIX_PROCESS_SET_DELETE", .code = -56},

    {.index = 34, .name = "PMIX_DEBUGGER_RELEASE", .code = -3},

    {.index = 35, .name = "PMIX_READY_FOR_DEBUG", .code = -58},

    {.index = 36, .name = "PMIX_QUERY_PARTIAL_SUCCESS", .code = -104},

    {.index = 37, .name = "PMIX_JCTRL_CHECKPOINT", .code = -106},

    {.index = 38, .name = "PMIX_JCTRL_CHECKPOINT_COMPLETE", .code = -107},

    {.index = 39, .name = "PMIX_JCTRL_PREEMPT_ALERT", .code = -108},

    {.index = 40, .name = "PMIX_MONITOR_HEARTBEAT_ALERT", .code = -109},

    {.index = 41, .name = "PMIX_MONITOR_FILE_ALERT", .code = -110},

    {.index = 42, .name = "PMIX_PROC_TERMINATED", .code = -111},

    {.index = 43, .name = "PMIX_ERR_EVENT_REGISTRATION", .code = -144},

    {.index = 44, .name = "PMIX_MODEL_DECLARED", .code = -147},

    {.index = 45, .name = "PMIX_MODEL_RESOURCES", .code = -151},

    {.index = 46, .name = "PMIX_OPENMP_PARALLEL_ENTERED", .code = -152},

    {.index = 47, .name = "PMIX_OPENMP_PARALLEL_EXITED", .code = -153},

    {.index = 48, .name = "PMIX_LAUNCHER_READY", .code = -155},

    {.index = 49, .name = "PMIX_OPERATION_IN_PROGRESS", .code = -156},

    {.index = 50, .name = "PMIX_OPERATION_SUCCEEDED", .code = -157},

    {.index = 51, .name = "PMIX_ERR_INVALID_OPERATION", .code = -158},

    {.index = 52, .name = "PMIX_GROUP_INVITED", .code = -159},

    {.index = 53, .name = "PMIX_GROUP_LEFT", .code = -160},

    {.index = 54, .name = "PMIX_GROUP_INVITE_ACCEPTED", .code = -161},

    {.index = 55, .name = "PMIX_GROUP_INVITE_DECLINED", .code = -162},

    {.index = 56, .name = "PMIX_GROUP_INVITE_FAILED", .code = -163},

    {.index = 57, .name = "PMIX_GROUP_MEMBERSHIP_UPDATE", .code = -164},

    {.index = 58, .name = "PMIX_GROUP_CONSTRUCT_ABORT", .code = -165},

    {.index = 59, .name = "PMIX_GROUP_CONSTRUCT_COMPLETE", .code = -166},

    {.index = 60, .name = "PMIX_GROUP_LEADER_SELECTED", .code = -167},

    {.index = 61, .name = "PMIX_GROUP_LEADER_FAILED", .code = -168},

    {.index = 62, .name = "PMIX_GROUP_CONTEXT_ID_ASSIGNED", .code = -169},

    {.index = 63, .name = "PMIX_GROUP_MEMBER_FAILED", .code = -170},

    {.index = 64, .name = "PMIX_ERR_REPEAT_ATTR_REGISTRATION", .code = -171},

    {.index = 65, .name = "PMIX_ERR_IOF_FAILURE", .code = -172},

    {.index = 66, .name = "PMIX_ERR_IOF_COMPLETE", .code = -173},

    {.index = 67, .name = "PMIX_LAUNCH_COMPLETE", .code = -174},

    {.index = 68, .name = "PMIX_FABRIC_UPDATED", .code = -175},

    {.index = 69, .name = "PMIX_FABRIC_UPDATE_PENDING", .code = -176},

    {.index = 70, .name = "PMIX_FABRIC_UPDATE_ENDPOINTS", .code = -113},

    {.index = 71, .name = "PMIX_ERR_JOB_APP_NOT_EXECUTABLE", .code = -177},

    {.index = 72, .name = "PMIX_ERR_JOB_NO_EXE_SPECIFIED", .code = -178},

    {.index = 73, .name = "PMIX_ERR_JOB_FAILED_TO_MAP", .code = -179},

    {.index = 74, .name = "PMIX_ERR_JOB_CANCELED", .code = -180},

    {.index = 75, .name = "PMIX_ERR_JOB_FAILED_TO_LAUNCH", .code = -181},

    {.index = 76, .name = "PMIX_ERR_JOB_ABORTED", .code = -182},

    {.index = 77, .name = "PMIX_ERR_JOB_KILLED_BY_CMD", .code = -183},

    {.index = 78, .name = "PMIX_ERR_JOB_ABORTED_BY_SIG", .code = -184},

    {.index = 79, .name = "PMIX_ERR_JOB_TERM_WO_SYNC", .code = -185},

    {.index = 80, .name = "PMIX_ERR_JOB_SENSOR_BOUND_EXCEEDED", .code = -186},

    {.index = 81, .name = "PMIX_ERR_JOB_NON_ZERO_TERM", .code = -187},

    {.index = 82, .name = "PMIX_ERR_JOB_ALLOC_FAILED", .code = -188},

    {.index = 83, .name = "PMIX_ERR_JOB_ABORTED_BY_SYS_EVENT", .code = -189},

    {.index = 84, .name = "PMIX_ERR_JOB_EXE_NOT_FOUND", .code = -190},

    {.index = 85, .name = "PMIX_ERR_JOB_WDIR_NOT_FOUND", .code = -233},

    {.index = 86, .name = "PMIX_ERR_JOB_INSUFFICIENT_RESOURCES", .code = -234},

    {.index = 87, .name = "PMIX_ERR_JOB_SYS_OP_FAILED", .code = -235},

    {.index = 88, .name = "PMIX_EVENT_JOB_START", .code = -191},

    {.index = 89, .name = "PMIX_EVENT_JOB_END", .code = -145},

    {.index = 90, .name = "PMIX_EVENT_SESSION_START", .code = -192},

    {.index = 91, .name = "PMIX_EVENT_SESSION_END", .code = -193},

    {.index = 92, .name = "PMIX_ERR_PROC_REQUESTED_ABORT", .code = -8},

    {.index = 93, .name = "PMIX_ERR_PROC_TERM_WO_SYNC", .code = -200},

    {.index = 94, .name = "PMIX_EVENT_PROC_TERMINATED", .code = -201},

    {.index = 95, .name = "PMIX_ERR_PROC_KILLED_BY_CMD", .code = -400},

    {.index = 96, .name = "PMIX_ERR_PROC_FAILED_TO_START", .code = -401},

    {.index = 97, .name = "PMIX_ERR_PROC_ABORTED_BY_SIG", .code = -402},

    {.index = 98, .name = "PMIX_ERR_PROC_SENSOR_BOUND_EXCEEDED", .code = -403},

    {.index = 99, .name = "PMIX_ERR_EXIT_NONZERO_TERM", .code = -404},

    {.index = 100, .name = "PMIX_EVENT_SYS_BASE", .code = -230},

    {.index = 101, .name = "PMIX_EVENT_NODE_DOWN", .code = -231},

    {.index = 102, .name = "PMIX_EVENT_NODE_OFFLINE", .code = -232},

    {.index = 103, .name = "PMIX_EVENT_SYS_OTHER", .code = -330},

    {.index = 104, .name = "PMIX_EVENT_NO_ACTION_TAKEN", .code = -331},

    {.index = 105, .name = "PMIX_EVENT_PARTIAL_ACTION_TAKEN", .code = -332},

    {.index = 106, .name = "PMIX_EVENT_ACTION_DEFERRED", .code = -333},

    {.index = 107, .name = "PMIX_EVENT_ACTION_COMPLETE", .code = -334},

    {.index = 108, .name = "PMIX_ERR_SILENT", .code = -2},

    {.index = 109, .name = "PMIX_ERR_DEBUGGER_RELEASE", .code = -3},

    {.index = 110, .name = "PMIX_ERR_PROC_ABORTED", .code = -7},

    {.index = 111, .name = "PMIX_ERR_PROC_ABORTING", .code = -9},

    {.index = 112, .name = "PMIX_ERR_SERVER_FAILED_REQUEST", .code = -10},

    {.index = 113, .name = "PMIX_EXISTS", .code = -11},

    {.index = 114, .name = "PMIX_ERR_HANDSHAKE_FAILED", .code = -13},

    {.index = 115, .name = "PMIX_ERR_READY_FOR_HANDSHAKE", .code = -14},

    {.index = 116, .name = "PMIX_ERR_PROC_ENTRY_NOT_FOUND", .code = -17},

    {.index = 117, .name = "PMIX_ERR_PACK_MISMATCH", .code = -22},

    {.index = 118, .name = "PMIX_ERR_IN_ERRNO", .code = -26},

    {.index = 119, .name = "PMIX_ERR_DATA_VALUE_NOT_FOUND", .code = -30},

    {.index = 120, .name = "PMIX_ERR_INVALID_ARG", .code = -33},

    {.index = 121, .name = "PMIX_ERR_INVALID_KEY", .code = -34},

    {.index = 122, .name = "PMIX_ERR_INVALID_KEY_LENGTH", .code = -35},

    {.index = 123, .name = "PMIX_ERR_INVALID_VAL", .code = -36},

    {.index = 124, .name = "PMIX_ERR_INVALID_VAL_LENGTH", .code = -37},

    {.index = 125, .name = "PMIX_ERR_INVALID_LENGTH", .code = -38},

    {.index = 126, .name = "PMIX_ERR_INVALID_NUM_ARGS", .code = -39},

    {.index = 127, .name = "PMIX_ERR_INVALID_ARGS", .code = -40},

    {.index = 128, .name = "PMIX_ERR_INVALID_NUM_PARSED", .code = -41},

    {.index = 129, .name = "PMIX_ERR_INVALID_KEYVALP", .code = -42},

    {.index = 130, .name = "PMIX_ERR_INVALID_SIZE", .code = -43},

    {.index = 131, .name = "PMIX_ERR_INVALID_NAMESPACE", .code = -44},

    {.index = 132, .name = "PMIX_ERR_SERVER_NOT_AVAIL", .code = -45},

    {.index = 133, .name = "PMIX_ERR_NOT_IMPLEMENTED", .code = -48},

    {.index = 134, .name = "PMIX_DEBUG_WAITING_FOR_NOTIFY", .code = -58},

    {.index = 135, .name = "PMIX_ERR_FATAL", .code = -63},

    {.index = 136, .name = "PMIX_ERR_NOT_AVAILABLE", .code = -64},

    {.index = 137, .name = "PMIX_ERR_VALUE_OUT_OF_BOUNDS", .code = -65},

    {.index = 138, .name = "PMIX_ERR_FILE_OPEN_FAILURE", .code = -67},

    {.index = 139, .name = "PMIX_ERR_FILE_READ_FAILURE", .code = -68},

    {.index = 140, .name = "PMIX_ERR_FILE_WRITE_FAILURE", .code = -69},

    {.index = 141, .name = "PMIX_ERR_SYS_LIMITS_PIPES", .code = -70},

    {.index = 142, .name = "PMIX_ERR_SYS_LIMITS_CHILDREN", .code = -71},

    {.index = 143, .name = "PMIX_ERR_PIPE_SETUP_FAILURE", .code = -72},

    {.index = 144, .name = "PMIX_ERR_EXE_NOT_ACCESSIBLE", .code = -73},

    {.index = 145, .name = "PMIX_ERR_JOB_WDIR_NOT_ACCESSIBLE", .code = -74},

    {.index = 146, .name = "PMIX_ERR_SYS_LIMITS_FILES", .code = -75},

    {.index = 147, .name = "PMIX_ERR_LOST_CONNECTION_TO_SERVER", .code = -101},

    {.index = 148, .name = "PMIX_ERR_LOST_PEER_CONNECTION", .code = -102},

    {.index = 149, .name = "PMIX_ERR_LOST_CONNECTION_TO_CLIENT", .code = -103},

    {.index = 150, .name = "PMIX_NOTIFY_ALLOC_COMPLETE", .code = -105},

    {.index = 151, .name = "PMIX_ERR_INVALID_TERMINATION", .code = -112},

    {.index = 152, .name = "PMIX_ERR_JOB_TERMINATED", .code = -145},

    {.index = 153, .name = "PMIX_ERR_UPDATE_ENDPOINTS", .code = -146},

    {.index = 154, .name = "PMIX_GDS_ACTION_COMPLETE", .code = -148},

    {.index = 155, .name = "PMIX_PROC_HAS_CONNECTED", .code = -149},

    {.index = 156, .name = "PMIX_CONNECT_REQUESTED", .code = -150},

    {.index = 157, .name = "PMIX_ERR_NODE_DOWN", .code = -231},

    {.index = 158, .name = "PMIX_ERR_NODE_OFFLINE", .code = -232},

    {.index = 159, .name = "PMIX_ERR_FABRIC_NOT_PARSEABLE", .code = -1363},

    {.index = 160, .name = "PMIX_ERR_TAKE_NEXT_OPTION", .code = -1366},

    {.index = 161, .name = "PMIX_ERR_TEMP_UNAVAILABLE", .code = -1367},

    {.index = UINT32_MAX, .name = "", .code = -1}
};

