/*
 * This file is autogenerated by autogen.pl. Do not edit this file by hand.
 */

#include "src/include/pmix_config.h"
#include "src/include/pmix_frameworks.h"

pmix_mca_base_framework_t *pmix_frameworks[] = {
    &pmix_bfrops_base_framework,
    &pmix_gds_base_framework,
    &pmix_pcompress_base_framework,
    &pmix_pdl_base_framework,
    &pmix_pif_base_framework,
    &pmix_pinstalldirs_base_framework,
    &pmix_plog_base_framework,
    &pmix_pmdl_base_framework,
    &pmix_pnet_base_framework,
    &pmix_preg_base_framework,
    &pmix_psec_base_framework,
    &pmix_psensor_base_framework,
    &pmix_psquash_base_framework,
    &pmix_pstat_base_framework,
    &pmix_ptl_base_framework,
    NULL
};

char *pmix_framework_names[] = {
    "bfrops",
    "gds",
    "pcompress",
    "pdl",
    "pif",
    "pinstalldirs",
    "plog",
    "pmdl",
    "pnet",
    "preg",
    "psec",
    "psensor",
    "psquash",
    "pstat",
    "ptl",
    "mca",
    NULL
};

